### ISSUE TITLE
How to Open The Trainer Window

### ISSUE THREAD

**Issue by YumeSeSeine** [Eveldee/NobetaTrainer#1]
I closed the trainer window and I've no idea how to get it back out. Pressing Alt just pulled out the cursor and I even restarted the launcher but I can't seem to get the trainer window back on-screen

**Comment by Eveldee** [comment]
I count this as a design issue that should be fixed by adding a default usable toggle key so I'm reopening this and I will push a fix.

**Comment by Eveldee** [comment]
Fixed by f807afe.
